### ISSUE TITLE
UnboundLocalError when running pytyle3

### ISSUE THREAD

**Issue by jeffo27** [BurntSushi/pytyle3#22]
Hello BurntSushi, I am using Openbox and looking for some mulithead surpport, so I followed the Arch Wiki and installed your Openbox-multihead and pytyle3. But when I ran pytyle3 in the terminal, the following traceback occured:

<code>

Openbox window manager is running...

Traceback (most recent call last):
  File "/usr/bin/pytyle3", line 19, in <module>
    client.update_clients()
  File "/usr/lib/python2.7/site-packages/pt3/client.py", line 192, in update_clients
    track_client(c)
  File "/usr/lib/python2.7/site-packages/pt3/client.py", line 208, in track_client
    clients[client] = Client(client)
  File "/usr/lib/python2.7/site-packages/pt3/client.py", line 52, in __init__
    tile.update_client_add(self)
  File "/usr/lib/python2.7/site-packages/pt3/tile.py", line 88, in update_client_add
    tiler.add(c)
  File "/usr/lib/python2.7/site-packages/pt3/layouts/layout_vert_horz.py", line 21, in add
    self.store.add(c)
  File "/usr/lib/python2.7/site-packages/pt3/layouts/store.py", line 16, in add
    ewmh.request_wm_state_checked(c.wid,0,util.get_atom('_NET_WM_STATE_BELOW')).check()
  File "/usr/lib/python2.7/site-packages/xpybutil/ewmh.py", line 1434, in request_wm_state_checked
    action, first, second, source)
  File "/usr/lib/python2.7/site-packages/xpybutil/event.py", line 90, in root_send_client_event_checked
    packed = pack_client_message(window, message_type, *data)
  File "/usr/lib/python2.7/site-packages/xpybutil/event.py", line 72, in pack_client_message
    if isinstance(message_type, basestring):
UnboundLocalError: local variable 'basestring' referenced before assignment
</code>

I checked the code in event.py in xpybutil and find where the problem is:
<code>

   def replay_pointer():
     
     #...some code...

     if sys.version_info[0] >= 3:
       basestring = str
     
     #...some other code...
</code>
I think xpybutil needs python3 but I installed it as python2.7 packages. 
I am not sure how to fix this, could you please give me some help?
By the way, I don't know how to open the multihead support using openbox-multihead because
I didn't quite understand the README of the package and I did not find any useful information about the usage... could you offer some docs or something like that?
Thanks for help!

**Comment by ViktorNova** [comment]
I am also having this error on Arch linux, Python2.7.9 =(
