### ISSUE TITLE
Cannot run pytyle3

### ISSUE THREAD

**Issue by gamehelp16** [BurntSushi/pytyle3#26]
I got this error when running pytyle3:

    Traceback (most recent call last):
      File "/usr/bin/pytyle3", line 13, in <module>
        import pt3.keybind
      File "/usr/lib/python2.7/site-packages/pt3/keybind.py", line 23, in <module>
        execfile(conffile)
      File "/etc/xdg/pytyle3/keybind.py", line 2, in <module>
        import state
      File "/usr/lib/python2.7/site-packages/pt3/state.py", line 22, in <module>
        w = ewmh.get_supporting_wm_check(xpybutil.root).reply()
      File "/usr/lib/python2.7/site-packages/xpybutil/util.py", line 47, in reply
        ret = get_property_value(self.cookie.reply())
    xcb.xproto.BadWindow: <xcb.xproto.WindowError object at 0x7fa888804878>

What should I do to fix it?

**Comment by BurntSushi** [comment]
This project isn't maintained. You're on your own.
